/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package covoiturage.gui;

import covoiturage.controler.*;
import covoiturage.dao.ReclamationDAO;
import covoiturage.dao.TrajetDAO;
import covoiturage.entities.Reclamation;
import covoiturage.entities.Trajet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author USER
 */
public class ListReclamations extends javax.swing.JFrame {

    /**
     * Creates new form ConsulterReclamation
     */
    ReclamationDAO reclamationDAO;
    Trajet trajet;
    ListReclamations lr;

    public ListReclamations() {
        reclamationDAO = new ReclamationDAO();
        trajet = new Trajet();
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RecTable = new javax.swing.JTable();
        btnRepondre = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnLire = new javax.swing.JButton();
        btnMap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        RecTable.setModel(new ListReclamationController());
        RecTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RecTable);

        btnRepondre.setText("Répondre");
        btnRepondre.setEnabled(false);
        btnRepondre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepondreActionPerformed(evt);
            }
        });

        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.setEnabled(false);
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnLire.setText("Lire");
        btnLire.setEnabled(false);
        btnLire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLireActionPerformed(evt);
            }
        });

        btnMap.setText("Map");
        btnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLire, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRepondre)
                .addGap(32, 32, 32)
                .addComponent(btnSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepondre)
                    .addComponent(btnQuitter)
                    .addComponent(btnSupprimer)
                    .addComponent(btnLire)
                    .addComponent(btnMap))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened
    
    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
//         String ob = RecTable.getValueAt(RecTable.getSelectedRow(), RecTable.getSelectedColumn()).toString();
//         txttest.setText((String)ob);
        dispose();
    }//GEN-LAST:event_btnQuitterActionPerformed
    
    private void btnRepondreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepondreActionPerformed
        // TODO add your handling code here:
        //dispose();
        Reclamation reclamation = new Reclamation();
        reclamation.setIdReclamation((int) RecTable.getValueAt(RecTable.getSelectedRow(), 0));
        reclamation.setDateReclamation((String) RecTable.getValueAt(RecTable.getSelectedRow(), 1));
        reclamation.setSujet_reclamation((String) RecTable.getValueAt(RecTable.getSelectedRow(), 2));
        reclamation.setContenuReclamation((String) RecTable.getValueAt(RecTable.getSelectedRow(), 3));
        Repondre r = new Repondre(reclamation);        
        r.setVisible(true);



        //Object v1= RecTable.getValueAt(RecTable.getSelectedRow(), RecTable.getSelectedColumn()).toString();
        
        
    }//GEN-LAST:event_btnRepondreActionPerformed
    
    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:

        /* String ob = RecTable.getValueAt(RecTable.getSelectedRow(), RecTable.getSelectedColumn()).toString();
         int i; 
         i = Integer.parseInt(ob); 
         reclamationDAO.deleteReclamation(i);*/
        int p = JOptionPane.showConfirmDialog(null, "Vous voulez supprimer cette réclamation?", "Supprimer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (p == 0) {
            int row = RecTable.getSelectedRow();
            
            reclamationDAO.deleteReclamation((int) RecTable.getValueAt(RecTable.getSelectedRow(), 0));
            RecTable.setModel(new ListReclamationController());
            btnRepondre.setEnabled(false);
            btnSupprimer.setEnabled(false);
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed
    
    private void RecTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecTableMouseClicked
        btnRepondre.setEnabled(true);
        btnSupprimer.setEnabled(true);
        btnLire.setEnabled(true);
        
        
    }//GEN-LAST:event_RecTableMouseClicked
    
    private void btnLireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLireActionPerformed
        
        Reclamation reclamation = new Reclamation();
        reclamation.setIdReclamation((int) RecTable.getValueAt(RecTable.getSelectedRow(), 0));
        reclamation.setDateReclamation((String) RecTable.getValueAt(RecTable.getSelectedRow(), 1));
        reclamation.setSujet_reclamation((String) RecTable.getValueAt(RecTable.getSelectedRow(), 2));
        reclamation.setContenuReclamation((String) RecTable.getValueAt(RecTable.getSelectedRow(), 3));
        LireReclamations lr = new LireReclamations(reclamation);
        lr.setVisible(true);
    }//GEN-LAST:event_btnLireActionPerformed

    private void btnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapActionPerformed
        
        JFrameMap fmap = new JFrameMap(trajet);
        fmap.setVisible(true);
        
    }//GEN-LAST:event_btnMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListReclamations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListReclamations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListReclamations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListReclamations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListReclamations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RecTable;
    private javax.swing.JButton btnLire;
    private javax.swing.JButton btnMap;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnRepondre;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
