/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package covoiturage.gui;

import covoiturage.dao.vehiculeDAO;
import covoiturage.entities.vehicule;
import java.util.Date;

/**
 *
 * @author Bilel
 */
public class MembreInfo extends javax.swing.JFrame {

    
    int id;
    String nom;
    String prenom;
    String adresse;
    Date date_naissance;
    Date date_inscription;
    int num_telephone;
    String mail;
    int evaluation;
    String password;

    public MembreInfo() {
        initComponents();
    }
    
    
        
    /**
     * Creates new form MembreInfo
     */
    public MembreInfo(int id,String nom, String prenom,String adresse, Date date_naissance, Date date_inscription,int num_telephone,String mail,int evaluation) {
        this.id=id;
        this.nom=nom;
        this.prenom=prenom;
        this.adresse=adresse;
        this.date_inscription=date_inscription;
        this.date_naissance=date_naissance;
        this.num_telephone=num_telephone;
        this.mail=mail;
        this.evaluation=evaluation;
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelDateNaissance = new javax.swing.JLabel();
        jLabelDateInscription = new javax.swing.JLabel();
        jLabelNumTelephone = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelEvaluation = new javax.swing.JLabel();
        jLabelMarque = new javax.swing.JLabel();
        jLabelModele = new javax.swing.JLabel();
        jLabelAnnee = new javax.swing.JLabel();
        jLabelNbPlaces = new javax.swing.JLabel();
        jLabelCouleur = new javax.swing.JLabel();
        jLabelMusique = new javax.swing.JLabel();
        jLabelClimatisation = new javax.swing.JLabel();
        jLabelFumeur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        jLabel3.setText("Adresse :");

        jLabel4.setText("Date de naissance :");

        jLabel5.setText("Date d'inscription :");

        jLabel6.setText("Numero de téléphone :");

        jLabel7.setText("Adresse mail :");

        jLabel8.setText("Evaluation :");

        jLabel9.setText("Marque :");

        jLabel10.setText("Modele :");

        jLabel11.setText("Annee :");

        jLabel12.setText("Nombre de places :");

        jLabel13.setText("Couleur :");

        jLabel14.setText("Musique :");

        jLabel15.setText("Climatisation :");

        jLabel16.setText("Fumeur :");

        jLabelNom.setText("jLabel17");

        jLabelPrenom.setText("jLabel18");

        jLabelAdresse.setText("jLabel19");

        jLabelDateNaissance.setText("jLabel20");

        jLabelDateInscription.setText("jLabel21");

        jLabelNumTelephone.setText("jLabel22");

        jLabelMail.setText("jLabel23");

        jLabelEvaluation.setText("jLabel24");

        jLabelMarque.setText("jLabel17");

        jLabelModele.setText("jLabel18");

        jLabelAnnee.setText("jLabel19");

        jLabelNbPlaces.setText("jLabel20");

        jLabelCouleur.setText("jLabel21");

        jLabelMusique.setText("jLabel22");

        jLabelClimatisation.setText("jLabel23");

        jLabelFumeur.setText("jLabel24");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluation)
                    .addComponent(jLabelMail)
                    .addComponent(jLabelNumTelephone)
                    .addComponent(jLabelDateInscription)
                    .addComponent(jLabelDateNaissance)
                    .addComponent(jLabelAdresse)
                    .addComponent(jLabelPrenom)
                    .addComponent(jLabelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModele)
                    .addComponent(jLabelMarque)
                    .addComponent(jLabelAnnee)
                    .addComponent(jLabelNbPlaces)
                    .addComponent(jLabelCouleur)
                    .addComponent(jLabelMusique)
                    .addComponent(jLabelClimatisation)
                    .addComponent(jLabelFumeur))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelMarque))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabelPrenom)
                    .addComponent(jLabelModele))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabelAdresse)
                    .addComponent(jLabelAnnee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabelDateNaissance)
                    .addComponent(jLabelNbPlaces))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabelDateInscription)
                    .addComponent(jLabelCouleur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(jLabelNumTelephone)
                    .addComponent(jLabelMusique))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jLabelMail)
                    .addComponent(jLabelClimatisation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(jLabelEvaluation)
                    .addComponent(jLabelFumeur))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        jLabelNom.setText(nom);
        jLabelPrenom.setText(prenom);
        jLabelAdresse.setText(adresse);
        jLabelDateNaissance.setText(date_naissance.toString());
        jLabelDateInscription.setText(date_inscription.toString());
        jLabelNumTelephone.setText(num_telephone + "");
        jLabelMail.setText(mail);
        jLabelEvaluation.setText(evaluation + "");
        
        vehiculeDAO vDAO = new vehiculeDAO();
        
        vehicule v = new vehicule();
        
        v= vDAO.findVediculeById(id);
        
        jLabelMarque.setText(v.getMarque());
        jLabelModele.setText(v.getModele());
        jLabelAnnee.setText(v.getAnnee()+"");
        jLabelNbPlaces.setText(v.getNombrePlace()+"");
        jLabelCouleur.setText(v.getCouleur());
        jLabelMusique.setText(v.getMusique()+"");
        jLabelClimatisation.setText(v.getClimatisation()+"");
        jLabelFumeur.setText(v.getFumeur()+"");
        
                
        
        
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MembreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MembreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MembreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MembreInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelAnnee;
    private javax.swing.JLabel jLabelClimatisation;
    private javax.swing.JLabel jLabelCouleur;
    private javax.swing.JLabel jLabelDateInscription;
    private javax.swing.JLabel jLabelDateNaissance;
    private javax.swing.JLabel jLabelEvaluation;
    private javax.swing.JLabel jLabelFumeur;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMarque;
    private javax.swing.JLabel jLabelModele;
    private javax.swing.JLabel jLabelMusique;
    private javax.swing.JLabel jLabelNbPlaces;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNumTelephone;
    private javax.swing.JLabel jLabelPrenom;
    // End of variables declaration//GEN-END:variables
}
