/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package covoiturage.gui;

import covoiturage.dao.membreDAO;
import covoiturage.entities.membre;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Bilel
 */
public class membre_modifier extends javax.swing.JFrame {
    int id;
    String nom;
    String prenom;
    String adresse;
    Date date_naissance;
    Date date_inscription;
    int num_telephone;
    String mail;
    int evaluation;
    String password;
    /**
     * Creates new form membre_modifier
     */
    public membre_modifier() {
        initComponents();
    }
    
    public membre_modifier( int id,String nom, String prenom,String adresse, Date date_naissance, Date date_inscription,int num_telephone,String mail,int evaluation) {
        initComponents();
        this.id=id;
        this.nom=nom;
        this.prenom=prenom;
        this.adresse=adresse;
        this.date_inscription=date_inscription;
        this.date_naissance=date_naissance;
        this.num_telephone=num_telephone;
        this.mail=mail;
        this.evaluation=evaluation;
        //this.password=password;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonRetourMembre = new javax.swing.JButton();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldTelephone = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEvaluation = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButtonModifierMembre = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelIdMembre = new javax.swing.JLabel();
        jButtonModifierMembreEtVehicule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        jLabel3.setText("Adresse");

        jLabel4.setText("Numero de téléphone :");

        jLabel5.setText("Adresse mail :");

        jButtonRetourMembre.setText("Retour Gestion Membres");
        jButtonRetourMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourMembreActionPerformed(evt);
            }
        });

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabel6.setText("Evaluation :");

        jLabel7.setText("Date_naissance :");

        jComboBoxEvaluation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " 0", " 1", " 2", " 3", " 4", " 5" }));
        jComboBoxEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEvaluationActionPerformed(evt);
            }
        });

        jLabel8.setText("Date_inscription :");

        jButtonModifierMembre.setText("Modifier le Membre");
        jButtonModifierMembre.setBorder(null);
        jButtonModifierMembre.setBorderPainted(false);
        jButtonModifierMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierMembreActionPerformed(evt);
            }
        });

        jLabel9.setText("ID :");

        jButtonModifierMembreEtVehicule.setText("Modifier Membre et passer au vehicule");
        jButtonModifierMembreEtVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierMembreEtVehiculeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIdMembre)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jTextFieldTelephone)
                    .addComponent(jTextFieldAdresse)
                    .addComponent(jTextFieldPrenom)
                    .addComponent(jTextFieldNom)
                    .addComponent(jComboBoxEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModifierMembreEtVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModifierMembre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRetourMembre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelIdMembre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModifierMembreEtVehicule)
                .addGap(18, 18, 18)
                .addComponent(jButtonModifierMembre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetourMembre)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourMembreActionPerformed
        // TODO add your handling code here:
        dispose();
        membre_supprimer s = new membre_supprimer();
        s.show();
        
    }//GEN-LAST:event_jButtonRetourMembreActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       jLabelIdMembre.setText(id+"");
       jTextFieldNom.setText(nom);
       jTextFieldAdresse.setText(adresse);
       jTextFieldMail.setText(mail);
       jTextFieldTelephone.setText(num_telephone+"");
       jTextFieldPrenom.setText(prenom);
       //jDateChooser1.setDate(date_naissance);
       //jDateChooser2.setDate(date_inscription);
       
       
    }//GEN-LAST:event_formWindowActivated

    private void jComboBoxEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEvaluationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEvaluationActionPerformed

    private void jButtonModifierMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierMembreActionPerformed
        // TODO add your handling code here:
        membre m = new membre();
        m.setNom(jTextFieldNom.getText());
        m.setAdresse(jTextFieldAdresse.getText());
        m.setDate_inscription(null);
        m.setDate_naissance(null);
        m.setEvaluation(jComboBoxEvaluation.getSelectedIndex());
        m.setMail(jTextFieldMail.getText());
        m.setNum_telephone(DatatypeConverter.parseInt(jTextFieldTelephone.getText()));
        m.setId(id);
        m.setPrenom(jTextFieldPrenom.getText());
        membreDAO membre = new membreDAO();
        membre.updateMembre(m);
        dispose();
        membre_supprimer s = new membre_supprimer();
        s.show();
    }//GEN-LAST:event_jButtonModifierMembreActionPerformed

    private void jButtonModifierMembreEtVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierMembreEtVehiculeActionPerformed
        // TODO add your handling code here:
        int i;
        i = DatatypeConverter.parseInt(jLabelIdMembre.getText());
        System.out.println(i);
        hide();
        membre_modifier_vehicule me = new membre_modifier_vehicule(i);
        me.show();
    }//GEN-LAST:event_jButtonModifierMembreEtVehiculeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membre_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membre_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membre_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membre_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membre_modifier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifierMembre;
    private javax.swing.JButton jButtonModifierMembreEtVehicule;
    private javax.swing.JButton jButtonRetourMembre;
    private javax.swing.JComboBox jComboBoxEvaluation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIdMembre;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
